app_id: "e6f8ca14-e399-464f-b98d-b135fe9cf7c1"
app_secret: "_C99Bnk-o_5ecamr644CNhS-4tOXZ_Jg_1" # env in production
redirect: "http://localhost:8000/callback" # change host in production
scopes: "openid profile offline_access user.read calendars.read"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"
