app_id: "055cd05b-c16d-4745-a66f-f8c7610ae570"
app_secret: "i1_81F-3X.-L-kV9II~tw655~KFEnU1DtY"
redirect: "http://localhost:8000/callback"
scopes: "openid profile offline_access user.read calendars.read"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"